---
  - name: Deploy a web application
    hosts: db_and_web_server1
    become: yes
    become_method: sudo

    tasks:
      - name: Install all required dependencies
        apt: #name={{item}} state=installed
          name: [ 'python', 'python-setuptools', 'python-dev', 'build-essential', 'python3-pip', 'python-apt']
          state: present
#        with_items:
#          - python
#          - python-setuptools
#          - python-dev
#          - build-essential
#          - python-pip
#          - python-mysqldb
#
#      - name: install python-is-python3
#        apt: name=python-is-python3 update_cache=yes state=present
#
#      - name: creating alias
#        shell: echo alias pip=pip3 >> ~/.bashrc
#
#      - name: test and upgrade pip
#        pip: name=pip state=latest
#        tags:
#          - packages


      - name: Install the MySQL-python through pip
        pip:
          name: ['pip' , 'MySQL-python' ]
          state: forcereinstall


      - name: Install MySQL database
        apt: name={{item}} state=installed
        with_items:
          - mysql-server
          - mysql-client

      - name: Start the database service
        service:
          name: mysql
          state: started
          enabled: yes

      - name: Create Application Database
        mysql_db: name=employee_db state=present


      - name: Create Database User
        mysql_user:
          name: db_user
          password: Passw0rd
          priv: '*.*:ALL'
          state: present

      - name: Install Python flask dependency
        pip:
          name: "{{item}}"
          state: present
        with_items:
          - flask
          - flask-mysql

#nohup & for running the app in background, Also, should have the py file in the same folder.
      - name: Start Web Server
        shell: FLASK_APP=app.py nohup flask run --host 0.0.0.0 &