---
  - name: Deploy a web application
    hosts: db_and_web_server1
    become: yes
    become_method: sudo

    tasks:
      - name: Install all required dependencies
        apt: #name={{item}} state=installed
          name: [ 'python', 'python-setuptools', 'python-dev', 'build-essential', 'python-pip', 'python-apt', 'python-mysqldb', 'python3-pip', 'python3-setuptools']
          state: present


      - name: Install MySQL database
        apt: name={{item}} state=present
        with_items:
          - mysql-server
          - mysql-client

#for some reason, this didnot work well, need to retest to check if we need this or not
#      - name: Start the database service
#        service:
#          name: mysql
#          state: started
#          enabled: yes

      - name: "Start DB Sevice"
        shell: service mysql start
        become: yes

      - name: Create Application Database
        mysql_db: #name=employee_db state=present login_unix_socket=/var/run/mysqld/mysqld.sock
          name: employee_db
          state: present
          #added below line to avoid login issues when running scripts multiple times
          login_unix_socket: /var/run/mysqld/mysqld.sock
        become: yes


      - name: Create Database User
        mysql_user:
          name: db_user
          password: Passw0rd
          priv: '*.*:ALL'
          state: present
          #added below line to avoid login issues when running scripts multiple times
          login_unix_socket: /var/run/mysqld/mysqld.sock
        become: yes

      #since there could be issue with linux vs pip versions, its always safer to upgrade pip to latest version avlbl for OS
      - name: Update pip
        command: pip install --upgrade pip


      - name: Install Python flask dependency
        pip:
          name: "{{item}}"
          state: present
        with_items:
          - flask
          - flask-mysql




      #nohup & for running the app in background, Also, should have the py file in the same folder.
      - name: Start Web Server
        #we have to store this in opt, since ansible deduces it for execution or else it will not be able to access in any other folder.[for trial, try using ./app.py]
        shell: FLASK_APP=/opt/app.py nohup flask run --host 0.0.0.0 &


        #to check if its working run: sudo lsof -t -i:5000, if it outputs a number then its fine!